# Generated by Django 5.1.2 on 2024-12-09 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_course_imageurl_course_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='imageUrl',
        ),
    ]
